# Generated by Django 4.2.2 on 2023-06-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_skip',
            new_name='votes_to_skip',
        ),
    ]
